export const menus = [
  {
    id: 1,
    title: "Dashboard",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-tachometer-alt",
    link: "/dashboard",
  },
  {
    id: 2,
    title: "Widgets",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-th",
    link: "/widgets",
    badgeTile: "new",
    badgeVariant: "danger",
  },
  {
    id: 44,
    title: "Layout Options",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-copy",
    link: "/layout-options",
    badgeTile: "6",
    badgeVariant: "success",
  },
  {
    id: 3,
    title: "Charts",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-chart-pie",
    link: "/charts",
  },
  {
    id: 4,
    title: "UI Elements",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-tree",
    link: "/ui-elements",
  },
  {
    id: 5,
    title: "Forms",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-edit",
    link: "/forms",
  },
  {
    id: 6,
    title: "Tables",
    index: 1,
    group: 4,
    parent: -1,
    iconCN: "fas fa-table",
    link: "/tables",
  },
  {
    id: 7,
    title: "Calendar",
    index: 1,
    group: 1,
    parent: -1,
    iconCN: "far fa-calendar-alt",
    link: "/calendar",
    badgeTile: "2",
    badgeVariant: "info",
  },
  {
    id: 8,
    title: "Gallery",
    index: 1,
    group: 1,
    parent: -1,
    iconCN: "far fa-image",
    link: "/gallery",
  },
  {
    id: 9,
    title: "Mailbox",
    index: 1,
    group: 1,
    parent: -1,
    iconCN: "far fa-envelope",
    link: "/mailbox",
  },
  {
    id: 10,
    title: "Pages",
    index: 1,
    group: 1,
    parent: -1,
    iconCN: "fas fa-book",
    link: "/pages",
  },
  {
    id: 11,
    title: "Extras",
    index: 1,
    group: 1,
    parent: -1,
    iconCN: "far fa-plus-square",
    link: "/extras",
  },
  {
    id: 12,
    title: "Documentation",
    index: 1,
    group: 2,
    parent: -1,
    iconCN: "fas fa-file",
    link: "/documentation",
  },
  {
    id: 13,
    title: "Level 1",
    index: 1,
    group: 5,
    parent: -1,
    iconCN: "fas fa-circle",
    link: "/level-1",
  },
  {
    id: 14,
    title: "Level 1",
    index: 1,
    group: 5,
    parent: -1,
    iconCN: "fas fa-circle",
    link: "/",
  },
  {
    id: 15,
    title: "Level 1",
    index: 1,
    group: 5,
    parent: -1,
    iconCN: "fas fa-circle",
    link: "/",
  },
  {
    id: 16,
    title: "Important",
    index: 1,
    group: 3,
    parent: -1,
    iconCN: "far fa-circle text-danger",
    link: "/important",
  },
  {
    id: 17,
    title: "Warning",
    index: 1,
    group: 3,
    parent: -1,
    iconCN: "far fa-circle text-warning",
    link: "/warning",
  },
  {
    id: 18,
    title: "Informational",
    index: 1,
    group: 3,
    parent: -1,
    iconCN: "far fa-circle text-info",
    link: "/information",
  },

  {
    id: 19,
    title: "Dashboard v1",
    index: 1,
    group: -1,
    parent: 1,
    iconCN: "far fa-circle nav-icon",
    link: "/v1",
  },
  {
    id: 20,
    title: "Dashboard v2",
    index: 1,
    group: -1,
    parent: 1,
    iconCN: "far fa-circle nav-icon",
    link: "/v2",
  },
  {
    id: 21,
    title: "Dashboard v3",
    index: 1,
    group: -1,
    parent: 1,
    iconCN: "far fa-circle nav-icon",
    link: "/v3",
  },
  {
    id: 22,
    title: "Top Navigation",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/top-nav",
  },
  {
    id: 23,
    title: "Top Navigation sidebar",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/top-nav-sidebar",
  },
  {
    id: 24,
    title: "Boxed",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/boxed",
  },
  {
    id: 25,
    title: "Fixed Sidebar",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/sidebar",
  },
  {
    id: 26,
    title: "Fixed Navbar",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/navbar",
  },
  {
    id: 27,
    title: "Fixed Footer",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/footer",
  },
  {
    id: 28,
    title: "Collapsed Sidebar",
    index: 1,
    group: -1,
    parent: 44,
    iconCN: "",
    link: "/collapsed-sidebar",
  },
  {
    id: 29,
    title: "ChartJS",
    index: 1,
    group: -1,
    parent: 3,
    iconCN: "",
    link: "/chartjs",
  },
  {
    id: 30,
    title: "Flot",
    index: 1,
    group: -1,
    parent: 3,
    iconCN: "",
    link: "/flot",
  },
  {
    id: 31,
    title: "Inline",
    index: 1,
    group: -1,
    parent: 3,
    iconCN: "",
    link: "/inline",
  },
  {
    id: 32,
    title: "General",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/general",
  },
  {
    id: 33,
    title: "Icons",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/icon",
  },
  {
    id: 34,
    title: "Buttons",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/buttons",
  },
  {
    id: 35,
    title: "Sliders",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/sliders",
  },
  {
    id: 36,
    title: "Modals & Alerts",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/modals-alerts",
  },
  {
    id: 37,
    title: "Navbar & Tabs",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/nav-tabs",
  },
  {
    id: 38,
    title: "Timeline",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/timeline",
  },
  {
    id: 39,
    title: "Ribbons",
    index: 1,
    group: -1,
    parent: 4,
    iconCN: "",
    link: "/ribbons",
  },
];
export const menuGroups = [
  { id: 1, title: "example", index: 1 },
  { id: 2, title: "miscellaneous", index: 2 },
  { id: 3, title: "labels", index: 3 },
  { id: 4, title: "", index: 0 },
  { id: 5, title: "MULTI LEVEL EXAMPLE", index: 0 },
];
